sap.ui.define([                                                                                                                                                                                                                                                
    "nype/ft/ac/controller/BaseController",                                                                                                                                                                                                                    
    "sap/ui/model/json/JSONModel",                                                                                                                                                                                                                             
    "sap/m/MessageBox",                                                                                                                                                                                                                                        
    "sap/ui/model/Filter",                                                                                                                                                                                                                                     
    "sap/ui/model/FilterOperator"                                                                                                                                                                                                                              
], function (BaseController, JSONModel, MessageBox, Filter, FilterOperator) {                                                                                                                                                                                  
    "use strict";                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
    return BaseController.extend("nype.ft.ac.controller.Detail", {                                                                                                                                                                                             
        onInit: function () {                                                                                                                                                                                                                                  
            var oViewModel = new JSONModel({                                                                                                                                                                                                                   
                busy: false,                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
                dataDownloaded: false,                                                                                                                                                                                                                         
                systemStatusSaved: false,                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
                semanticAction: null,                                                                                                                                                                                                                          
                semanticObject: null,                                                                                                                                                                                                                          
                system: null,                                                                                                                                                                                                                                  
                tableDataReceived: false                                                                                                                                                                                                                       
            });                                                                                                                                                                                                                                                
            this.setModel(oViewModel, "view");                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
            var oRouter = this.getRouter();                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                               
            oRouter.getRoute("detail").attachMatched(this._onObjectMatched, this);                                                                                                                                                                             
            oRouter.attachBeforeRouteMatched(this._onBeforeRouteMatched, this);                                                                                                                                                                                
        },                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
        onClosePress: function () {                                                                                                                                                                                                                            
            var oViewModel = this.getModel("view");                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
            var sSemanticObject = oViewModel.getProperty("/semanticObject");                                                                                                                                                                                   
            var sSemanticAction = oViewModel.getProperty("/semanticAction");                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
            this.getRouter().navTo("systems", {                                                                                                                                                                                                                
                semanticObject: encodeURIComponent(sSemanticObject),                                                                                                                                                                                           
                semanticAction: encodeURIComponent(sSemanticAction),                                                                                                                                                                                           
            }, true);                                                                                                                                                                                                                                          
        },                                                                                                                                                                                                                                                     
        onSortPress: function () {                                                                                                                                                                                                                             
            this.oSmartTable.openPersonalisationDialog("Sort");                                                                                                                                                                                                
        },                                                                                                                                                                                                                                                     
        onRefreshPress: function () {                                                                                                                                                                                                                          
            this.getModel().refresh(true);                                                                                                                                                                                                                     
        },                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
        onBeforeRebindTable: function (oEvent) {                                                                                                                                                                                                               
            var oViewModel = this.getModel("view");                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
            var sSemanticObject = oViewModel.getProperty("/semanticObject");                                                                                                                                                                                   
            var sSemanticAction = oViewModel.getProperty("/semanticAction");                                                                                                                                                                                   
            var sSystem = oViewModel.getProperty("/system");                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
            var oBindingParams = oEvent.getParameter("bindingParams");                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
            oBindingParams.filters = [                                                                                                                                                                                                                         
                new Filter("SemanticObject", FilterOperator.EQ, sSemanticObject),                                                                                                                                                                              
                new Filter("SemanticAction", FilterOperator.EQ, sSemanticAction),                                                                                                                                                                              
                new Filter("SystemId", FilterOperator.EQ, sSystem)                                                                                                                                                                                             
            ];                                                                                                                                                                                                                                                 
        },                                                                                                                                                                                                                                                     
        onTableDataReceived: function () {                                                                                                                                                                                                                     
            this.getModel("view").setProperty("/tableDataReceived", true);                                                                                                                                                                                     
        },                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
        noDataTextFormatter: function (bIsAvailable, bDownloadStatus, bCatDownloadInProgress, bTableDataReceived) {                                                                                                                                            
            if (!bIsAvailable || !bDownloadStatus) {                                                                                                                                                                                                           
                return this.getText("detail.message.systemNotAvailable");                                                                                                                                                                                      
            }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            if (bCatDownloadInProgress) {                                                                                                                                                                                                                      
                return this.getText("detail.message.downloadInProgress");                                                                                                                                                                                      
            }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            if (bTableDataReceived) {                                                                                                                                                                                                                          
                return this.getText("detail.message.noData");                                                                                                                                                                                                  
            }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            return " ";                                                                                                                                                                                                                                        
        },                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
        _onObjectMatched: function (oEvent) {                                                                                                                                                                                                                  
            var oModel = this.getModel();                                                                                                                                                                                                                      
            var oViewModel = this.getModel("view");                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
            var oArguments = oEvent.getParameter("arguments");                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
            var sSemanticObject = decodeURIComponent(oArguments.semanticObject);                                                                                                                                                                               
            var sSemanticAction = decodeURIComponent(oArguments.semanticAction);                                                                                                                                                                               
            var sSystem = oArguments.system;                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
            oViewModel.setProperty("/dataDownloaded", false);                                                                                                                                                                                                  
            oViewModel.setProperty("/systemStatusSaved", false);                                                                                                                                                                                               
            oViewModel.setProperty("/semanticObject", sSemanticObject);                                                                                                                                                                                        
            oViewModel.setProperty("/semanticAction", sSemanticAction);                                                                                                                                                                                        
            oViewModel.setProperty("/system", sSystem);                                                                                                                                                                                                        
            oViewModel.setProperty("/tableDataReceived", false);                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
            this._createContent();                                                                                                                                                                                                                             
            this.getOwnerComponent().setApplicationLayout(1);                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            oModel.metadataLoaded().then(function () {                                                                                                                                                                                                         
                var sObjectPath = "/" + oModel.createKey("SystemSet", {                                                                                                                                                                                        
                    Sid: sSystem                                                                                                                                                                                                                               
                });                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
                this.getView().bindElement({                                                                                                                                                                                                                   
                    path: sObjectPath,                                                                                                                                                                                                                         
                    events: {                                                                                                                                                                                                                                  
                        change: function () {                                                                                                                                                                                                                  
                            var oElementBinding = this.getView().getElementBinding();                                                                                                                                                                          
                            var oContext = oElementBinding.getBoundContext();                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
                            if (!oContext) {                                                                                                                                                                                                                   
                                this.oRouter.getTargets().display("notFound");                                                                                                                                                                                 
                                return;                                                                                                                                                                                                                        
                            }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
                            var oSystem = oContext.getObject();                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
                            this._downloadData(oSystem);                                                                                                                                                                                                       
                        }.bind(this)                                                                                                                                                                                                                           
                    }                                                                                                                                                                                                                                          
                });                                                                                                                                                                                                                                            
            }.bind(this));                                                                                                                                                                                                                                     
        },                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
        _onBeforeRouteMatched: function () {                                                                                                                                                                                                                   
            var oContainer = this.byId("container");                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
            // remove previous content                                                                                                                                                                                                                         
            oContainer.destroyContent();                                                                                                                                                                                                                       
        },                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
        _createContent: function () {                                                                                                                                                                                                                          
            var oContainer = this.byId("container");                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
            this.oSmartTable = sap.ui.xmlfragment("nype.ft.ac.view.fragments.DetailSmartTable", this);                                                                                                                                                         
                                                                                                                                                                                                                                                               
            oContainer.addContent(this.oSmartTable);                                                                                                                                                                                                           
        },                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
        _downloadData: function (oSystem) {                                                                                                                                                                                                                    
            var oViewModel = this.getModel("view");                                                                                                                                                                                                            
            var bDataDownloaded = oViewModel.getProperty("/dataDownloaded");                                                                                                                                                                                   
            var bDataReceived = oSystem.IsAvailable && !oSystem.CatDownloadInProgress;                                                                                                                                                                         
                                                                                                                                                                                                                                                               
            if (bDataDownloaded) {                                                                                                                                                                                                                             
                this._saveSystemStatus(oSystem.Sid, bDataReceived);                                                                                                                                                                                            
                return;                                                                                                                                                                                                                                        
            }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            if (!bDataReceived) {                                                                                                                                                                                                                              
                this._saveSystemStatus(oSystem.Sid, false);                                                                                                                                                                                                    
                this.oSmartTable.rebindTable(true);                                                                                                                                                                                                            
                return;                                                                                                                                                                                                                                        
            }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            this.getModel().callFunction("/DownloadApplications", {                                                                                                                                                                                            
                urlParameters: {                                                                                                                                                                                                                               
                    Sid: oSystem.Sid                                                                                                                                                                                                                           
                },                                                                                                                                                                                                                                             
                error: function (oError) {                                                                                                                                                                                                                     
                    var sMessage = this._getErrorMessage(oError);                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
                    if (sMessage) {                                                                                                                                                                                                                            
                        MessageBox.error(sMessage);                                                                                                                                                                                                            
                    }                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
                    oViewModel.setProperty("/busy", false);                                                                                                                                                                                                    
                }.bind(this)                                                                                                                                                                                                                                   
            });                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
            oViewModel.setProperty("/dataDownloaded", true);                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
            setTimeout(function () {                                                                                                                                                                                                                           
                this.getModel().refresh(true);                                                                                                                                                                                                                 
                this.oSmartTable.rebindTable(true);                                                                                                                                                                                                            
            }.bind(this), 1000);                                                                                                                                                                                                                               
        },                                                                                                                                                                                                                                                     
        _saveSystemStatus: function (sSid, bDataReceived) {                                                                                                                                                                                                    
            var oViewModel = this.getModel("view");                                                                                                                                                                                                            
            var bSystemStatusSaved = oViewModel.getProperty("/systemStatusSaved");                                                                                                                                                                             
                                                                                                                                                                                                                                                               
            if (bSystemStatusSaved) {                                                                                                                                                                                                                          
                return;                                                                                                                                                                                                                                        
            }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            var oModel = this.getModel("app");                                                                                                                                                                                                                 
            var oSystems = oModel.getProperty("/systems");                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
            oSystems[sSid] = {                                                                                                                                                                                                                                 
                dataReceived: bDataReceived                                                                                                                                                                                                                    
            };                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
            oModel.setProperty("/systems", oSystems);                                                                                                                                                                                                          
            oViewModel.setProperty("/systemStatusSaved", true);                                                                                                                                                                                                
        },                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
        _getErrorMessage: function (oError) {                                                                                                                                                                                                                  
            var oResponseObject;                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
            try {                                                                                                                                                                                                                                              
                oResponseObject = JSON.parse(oError.responseText);                                                                                                                                                                                             
            } catch (oError) {                                                                                                                                                                                                                                 
                console.error(oError);                                                                                                                                                                                                                         
                return null;                                                                                                                                                                                                                                   
            }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            if (oResponseObject.error && oResponseObject.error.message && oResponseObject.error.message.value) {                                                                                                                                               
                return oResponseObject.error.message.value;                                                                                                                                                                                                    
            }                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
            return null;                                                                                                                                                                                                                                       
        }                                                                                                                                                                                                                                                      
    });                                                                                                                                                                                                                                                        
});                                                                                                                                                                                                                                                            